sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - main
script:
  - npm run generate:gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: main
  local-dir: .output/public
