sudo: false
language: node_js
node_js:
  - 16
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
branches:
  only:
    - main
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run generate:gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: main
  local-dir: .output/public
